-- ─────────────────────────────────────────────────────────────────
-- QUORUM — Sprint D1: Avoidance Detection Foundation
-- Additional Risk D (R11) — Chunk 1 of 3
--
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- Run AFTER schema.sql + sprint1_add_ledger_tables.sql +
--          sprint2_add_register_to_sessions.sql
--
-- What this migration does:
--   1. Adds last_action_at to sessions — tracks when the user last
--      meaningfully interacted with a session (examiner submit,
--      outcome filed). Used by D2 avoidance detector to compute
--      days_open = NOW() - last_action_at.
--      NOT created_at: a session submitted 60 days ago but reviewed
--      3 days ago is not avoidance.
--      Backfilled from created_at for all existing rows.
--
--   2. Creates avoidance_alerts table — persisted detection results
--      written by the D2 background cron. Read by D3 Mirror alerts
--      route and the D3 dismiss endpoint.
-- ─────────────────────────────────────────────────────────────────


-- ── 1. Add last_action_at to sessions ────────────────────────────
--
-- Defaults to NULL so we can distinguish "never had activity tracked"
-- (pre-migration rows, backfilled below) from "session just created"
-- (post-migration rows, set on first examiner submit or outcome file).
--
-- NOT NULL is intentionally not enforced here — anonymous sessions
-- and sessions that predate this migration would fail the constraint.
-- The D2 detector always uses COALESCE(last_action_at, created_at)
-- so NULL values degrade gracefully to created_at semantics.

alter table sessions
  add column if not exists last_action_at timestamptz;

comment on column sessions.last_action_at is
  'Last meaningful user action on this session: examiner submit, outcome filed. '
  'NULL for sessions that predate Sprint D1 (D2 detector uses COALESCE with created_at). '
  'Set by examiner/route.ts POST and outcome/route.ts POST. '
  'NOT updated on passive views or persona streaming — those are not action signals.';

-- Backfill existing rows: last_action_at = created_at.
-- For historical sessions, created_at is the best proxy we have.
-- New sessions will have last_action_at updated on first real action.

update sessions
  set last_action_at = created_at
  where last_action_at is null;

-- Index: D2 detector queries sessions by user_id + status + last_action_at.

create index if not exists idx_sessions_last_action_at
  on sessions (user_id, last_action_at)
  where status = 'completed';


-- ── 2. Create avoidance_alerts table ─────────────────────────────
--
-- One row per detected avoidance event. Written by D2 cron
-- (runAvoidanceDetectionPass). Read by D3 Mirror alerts route.
-- Dismissed by D3 dismiss endpoint (sets dismissed_at + action_taken).
--
-- Design decisions:
--   - session_id is NOT unique: a session can generate a new alert
--     after dismissal if it remains unresolved past the next cron pass.
--     D2 checks for existing non-dismissed alerts and skips — idempotent
--     via query logic, not a DB constraint.
--   - user_id references auth.users — only authenticated users with
--     Mirror access can accumulate avoidance alerts. Anonymous sessions
--     are excluded in D2.
--   - structural_echo JSONB: the best prior resolved session match
--     (populated by D2 if structural_scores has a match ≥ 60/100).
--     Shape: { sessionId, matchScore, decisionSnippet, outcomeSummary }
--     NULL when no suitable prior resolved match exists.
--   - days_open: integer computed at detection time, stored for display.
--     NOT recomputed on each render — D3 shows this as "detected when
--     X days open" not "currently open for X days".
--   - upstream_dependency_score: from sessions_ontology.ontology_vector
--     at detection time. Stored for D3 display context.

create table if not exists avoidance_alerts (
  id                        uuid primary key default uuid_generate_v4(),
  user_id                   uuid references auth.users on delete cascade not null,
  session_id                uuid references sessions on delete cascade not null,

  -- Detection context (snapshot at cron time)
  days_open                 int not null,
  upstream_dependency_score numeric(4,2),     -- 0–10, from ontology_vector

  -- Structural echo: best prior resolved session with match ≥ 60/100.
  -- NULL when no qualifying match found by D2 detector.
  -- Shape: { sessionId, matchScore, decisionSnippet, outcomeSummary }
  structural_echo           jsonb,

  -- Lifecycle
  detected_at               timestamptz default now() not null,
  dismissed_at              timestamptz,      -- set by D3 dismiss endpoint
  action_taken              text
    check (action_taken in ('new_session', 'resolved_externally'))
);

comment on table avoidance_alerts is
  'Avoidance alerts generated by D2 background cron (runAvoidanceDetectionPass). '
  'R11 trigger: upstream_dependency >= 4, days_open >= 45, no outcome filed, '
  'no recent follow-up session. Surfaced in Mirror by D3 AvoidanceAlertCard.';

comment on column avoidance_alerts.structural_echo is
  'Best prior resolved session with structural similarity >= 60/100 to this session. '
  'JSON shape: { sessionId, matchScore, decisionSnippet, outcomeSummary }. '
  'NULL = no qualifying match found at detection time. '
  'Used by D3 to surface "you navigated something close to this before" context.';

comment on column avoidance_alerts.days_open is
  'Days between last_action_at (or created_at) and detection time. '
  'Stored as snapshot — not recomputed on read.';

-- Indexes
create index if not exists idx_avoidance_alerts_user_dismissed
  on avoidance_alerts (user_id, dismissed_at);

create index if not exists idx_avoidance_alerts_session_id
  on avoidance_alerts (session_id);

create index if not exists idx_avoidance_alerts_detected_at
  on avoidance_alerts (detected_at desc);

-- RLS: service role bypass (same pattern as all other Quorum tables).
-- D3 Mirror routes use createServiceClient() which bypasses RLS.
-- No user-facing direct reads — all access via API routes.

alter table avoidance_alerts enable row level security;

create policy "Avoidance alerts accessible via service role"
  on avoidance_alerts for all
  using (true);
