#!/usr/bin/env bash
# infra/docker/entrypoint.sh
# ── Wires this container's env vars into vLLM's actual launch command ────────
#
# Kept deliberately thin — all it does is validate required env vars are
# present (fail fast with a clear message, not a cryptic vLLM stack trace)
# and hand off to vLLM's own OpenAI-compatible server entrypoint.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

: "${MODEL_NAME:?MODEL_NAME is required — e.g. mistralai/Mistral-Small-Instruct or Qwen/Qwen2.5-72B-Instruct, whichever this container instance is serving (fast or premium role — see infra/README.md's sizing note)}"
: "${API_KEY:?API_KEY is required — the per-customer key generated by the deploy script (infra/deploy.sh), checked against Authorization: Bearer <API_KEY> on every request}"

echo "[entrypoint] Starting vLLM OpenAI-compatible server"
echo "[entrypoint] model=${MODEL_NAME}"
echo "[entrypoint] port=${PORT:-8000}"

exec python3 -m vllm.entrypoints.openai.api_server \
  --model "${MODEL_NAME}" \
  --port "${PORT:-8000}" \
  --api-key "${API_KEY}" \
  --served-model-name "${MODEL_NAME}" \
  --gpu-memory-utilization "${GPU_MEMORY_UTILIZATION:-0.90}" \
  --max-model-len "${MAX_MODEL_LEN:-8192}"
  # ^ These two are the most common values a customer's IT team will want to
  # tune (VRAM headroom, context window vs. throughput trade-off) — exposed
  # as env vars with sane defaults rather than hardcoded, so a redeploy
  # doesn't require touching this script.
