// app/terms/page.tsx
// ── Sprint 3 (S3-02) — Terms of Service ──────────────────────────────────────
// Server component — static.
// Key obligations: AI disclaimer, data ownership, liability limitation.
// ─────────────────────────────────────────────────────────────────────────────

import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Quorum',
  description: 'Terms governing your use of the Quorum decision intelligence platform.',
}

export default function TermsPage() {
  return (
    <main style={{
      minHeight: '100vh',
      background: 'var(--bg-void)',
      padding: '48px 20px 96px',
    }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>

        {/* Back link */}
        <Link href="/" style={{
          display: 'inline-flex', alignItems: 'center', gap: 6,
          fontSize: 11, color: 'var(--text-4)',
          fontFamily: 'var(--font-mono)', letterSpacing: '0.08em',
          textDecoration: 'none', marginBottom: 36,
        }}>
          ← Back to Quorum
        </Link>

        {/* Header */}
        <div style={{ marginBottom: 40 }}>
          <p style={{
            fontFamily: 'var(--font-mono)', fontSize: 10,
            letterSpacing: '0.18em', textTransform: 'uppercase',
            color: 'var(--text-4)', margin: '0 0 12px',
          }}>
            Legal
          </p>
          <h1 style={{
            fontFamily: 'var(--font-display)',
            fontSize: 'clamp(28px, 4vw, 42px)',
            fontWeight: 400, letterSpacing: '-0.02em',
            color: 'var(--text-1)', margin: '0 0 12px', lineHeight: 1.15,
          }}>
            Terms of Service
          </h1>
          <p style={{
            fontFamily: 'var(--font-mono)', fontSize: 11,
            color: 'var(--text-4)', letterSpacing: '0.06em', margin: 0,
          }}>
            Effective 5 June 2026 · Version 1.0
          </p>
        </div>

        <hr style={{ border: 'none', borderTop: '1px solid var(--border-dim)', marginBottom: 40 }} />

        <div style={{ fontSize: 14, color: 'var(--text-2)', lineHeight: 1.85, fontFamily: 'var(--font-body)' }}>

          <p style={{
            fontSize: 15, color: 'var(--text-2)', lineHeight: 1.8, marginBottom: 36,
            borderLeft: '2px solid var(--gold-dim)', paddingLeft: 16,
          }}>
            By using Quorum, you agree to these terms. Please read them carefully —
            in particular the AI disclaimer in Section 4 and the limitation of liability in Section 9.
          </p>

          <S title="1. What Quorum is">
            <p>
              Quorum is a private decision intelligence platform that uses AI to simulate a structured
              advisory council for high-stakes personal and professional decisions. Quorum is provided
              by Quorum ("we", "us", "our").
            </p>
            <p>
              Access is via the web application at app.quorumvault.xyz and through any other interfaces
              we make available.
            </p>
          </S>

          <S title="2. Your account">
            <p>
              Authentication uses passwordless magic links sent to your email address. You are
              responsible for maintaining access to that email account and for all activity that occurs
              under your Quorum account.
            </p>
            <p>
              You must provide accurate information and must not share access to your account with
              others. We may suspend or terminate accounts that violate these terms.
            </p>
          </S>

          <S title="3. Your data — you own it">
            <p>
              You retain full ownership of the decisions you submit and the outputs generated in response.
              We do not claim any intellectual property rights over your decision content or the
              AI-generated analysis of it.
            </p>
            <p>
              We hold your data in trust to deliver the service. We do not sell it, share it with
              advertisers, or use it for any purpose other than providing Quorum to you. For details
              on how we handle your data, see the{' '}
              <Link href="/privacy" style={{ color: 'var(--gold)', textDecoration: 'none' }}>
                Privacy Policy
              </Link>.
            </p>
          </S>

          <S title="4. AI analysis — not professional advice">
            <HighlightBox>
              Analysis generated by Quorum is produced by an AI system and is provided for
              informational and reflective purposes only. It does not constitute legal, financial,
              medical, investment, psychological, or any other form of professional advice.
              You should always apply your own judgment and, where appropriate, consult a qualified
              professional before making significant decisions.
              Quorum accepts no liability for decisions made in reliance on its analysis.
            </HighlightBox>
            <p>
              AI analysis may contain errors, omissions, or outputs that do not accurately reflect
              your situation. The quality of analysis depends on the context you provide.
            </p>
          </S>

          <S title="5. Acceptable use">
            <p>You may use Quorum for personal, professional, and business decision-making. You may not:</p>
            <ul style={{ paddingLeft: 20, margin: '8px 0', display: 'flex', flexDirection: 'column', gap: 6 }}>
              {[
                'Use Quorum for any unlawful purpose or in violation of any applicable law',
                'Submit content that is defamatory, threatening, or infringes third-party rights',
                'Attempt to reverse-engineer, scrape, or extract data from the platform at scale',
                'Resell or sublicense access to Quorum without a written agreement with us',
                'Use the service in a way that interferes with or disrupts other users or our infrastructure',
              ].map((item, i) => (
                <li key={i} style={{ color: 'var(--text-3)', lineHeight: 1.7 }}>{item}</li>
              ))}
            </ul>
          </S>

          <S title="6. Subscriptions and payment">
            <p>
              Certain features of Quorum require a paid subscription. Subscription plans, pricing, and
              billing cycles are set out at the time of purchase and may be updated from time to time.
            </p>
            <p>
              Subscriptions renew automatically at the end of each billing period unless cancelled.
              You may cancel at any time from your account settings. Cancellation takes effect at the
              end of the current billing period — no refunds are issued for partial periods unless
              required by applicable law.
            </p>
            <p>
              We reserve the right to modify pricing with 30 days' notice. Continued use after the
              notice period constitutes acceptance of the new pricing.
            </p>
          </S>

          <S title="7. Availability and changes">
            <p>
              We aim to provide reliable access to Quorum but do not guarantee uninterrupted
              availability. We may modify, suspend, or discontinue features at any time.
              We will provide reasonable notice of material changes where practicable.
            </p>
          </S>

          <S title="8. Intellectual property">
            <p>
              Quorum — including the software, design, personas, ontology system, and all product
              elements — is our proprietary intellectual property. Nothing in these terms grants you
              any rights to our technology beyond the right to use the service as described here.
            </p>
          </S>

          <S title="9. Limitation of liability">
            <p>
              To the maximum extent permitted by applicable law, Quorum and its team shall not be
              liable for any indirect, incidental, special, consequential, or punitive damages,
              including but not limited to loss of revenue, loss of profits, loss of data, or loss
              of business opportunity, arising from your use of or inability to use the service.
            </p>
            <p>
              Our total aggregate liability for any claim arising out of or relating to these terms
              or your use of Quorum shall not exceed the greater of (a) the amount you paid to us
              in the 12 months preceding the claim or (b) ₹5,000 INR.
            </p>
          </S>

          <S title="10. Indemnification">
            <p>
              You agree to indemnify and hold harmless Quorum and its team from any claim, loss,
              or damage arising from your violation of these terms, your misuse of the service,
              or your infringement of any third-party right.
            </p>
          </S>

          <S title="11. Governing law and disputes">
            <p>
              These terms are governed by the laws of India. Any dispute arising from these terms
              or your use of Quorum shall be subject to the exclusive jurisdiction of the courts
              in India, without regard to conflicts of law principles.
            </p>
          </S>

          <S title="12. Changes to these terms">
            <p>
              We may update these terms from time to time. We will post any material changes here
              and update the effective date. Continued use of Quorum after changes constitutes
              acceptance of the revised terms.
            </p>
          </S>

          <S title="13. Contact">
            <p>
              Questions about these terms? Use the{' '}
              <Link href="/settings/privacy" style={{ color: 'var(--gold)', textDecoration: 'none' }}>
                Privacy Center
              </Link>
              {' '}in Settings, accessible from the footer of any page.
            </p>
          </S>

        </div>
      </div>
    </main>
  )
}

function S({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{
        fontSize: 13, fontWeight: 600, color: 'var(--text-1)',
        fontFamily: 'var(--font-body)', letterSpacing: '0.01em',
        margin: '0 0 14px', paddingBottom: 8,
        borderBottom: '1px solid var(--border-dim)',
      }}>
        {title}
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {children}
      </div>
    </section>
  )
}

function HighlightBox({ children }: { children: React.ReactNode }) {
  return (
    <div style={{
      background: 'var(--bg-card)',
      border: '1px solid var(--gold-dim)',
      borderLeft: '3px solid var(--gold)',
      borderRadius: 10,
      padding: '14px 16px',
      fontSize: 13.5,
      color: 'var(--text-2)',
      lineHeight: 1.75,
      marginBottom: 12,
    }}>
      {children}
    </div>
  )
}
