#!/usr/bin/env bash
# infra/shared/bootstrap.sh.tpl
# ── Shared VM bootstrap — identical logic across AWS/GCP/Azure ───────────────
#
# This is a Terraform template (`.tpl`) — each cloud's main.tf renders it
# with that customer's specific values (see the ${...} placeholders) and
# passes the result as that cloud's native user-data/startup-script/
# cloud-init mechanism. The AWS/GCP/Azure Terraform modules differ only in
# HOW they provision a GPU VM and hand it this script — what the script
# itself does is 100% identical across all three, which is the whole point
# of pulling it out into one shared file instead of three copies.
#
# What this does, in order:
#   1. Install Docker + NVIDIA container toolkit (so --gpus all works)
#   2. Install Caddy (automatic HTTPS via Let's Encrypt — one line of config
#      gets TLS termination without hand-managing certs on 3 different clouds)
#   3. Write per-role config to /etc/quorum/ (env files the updater and
#      containers both read)
#   4. Pull and start the two model containers (fast role, premium role)
#   5. Install and enable the auto-updater's systemd timer
#   6. Run one update check immediately, so the deploy doesn't need to wait
#      15 minutes for the first timer tick
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Values substituted by Terraform at provision time ────────────────────────
CUSTOMER_USER_ID="${customer_user_id}"
MODEL_FAMILY="${model_family}"              # qwen | mistral
FAST_MODEL="${fast_model}"                  # e.g. Qwen/Qwen2.5-14B-Instruct or mistralai/Mistral-Small-Instruct
PREMIUM_MODEL="${premium_model}"            # e.g. Qwen/Qwen2.5-72B-Instruct or mistralai/Mistral-Large-Instruct
API_KEY="${api_key}"                        # generated by infra/deploy.sh before calling terraform apply — see that script
ADMIN_KEY="${admin_key}"                    # scoped narrowly to the health-ping endpoint, see infra/updater/check-and-update.sh
DOMAIN="${domain}"                          # e.g. <customer-slug>.private.quorum.example.com — Caddy needs this for auto-TLS
QUORUM_IMAGE="${quorum_image}"              # ghcr.io/quorum/private-inference:stable

# ── 1. Docker + NVIDIA container toolkit ──────────────────────────────────────
curl -fsSL https://get.docker.com | sh
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
  sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
  tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
apt-get update && apt-get install -y nvidia-container-toolkit
nvidia-ctk runtime configure --runtime=docker
systemctl restart docker

# ── 2. Caddy — one-line automatic HTTPS ───────────────────────────────────────
apt-get install -y debian-keyring debian-archive-keyring apt-transport-https
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
apt-get update && apt-get install -y caddy

cat > /etc/caddy/Caddyfile <<CADDYEOF
${domain} {
  reverse_proxy /fast/*   localhost:8001
  reverse_proxy /premium/* localhost:8002
}
CADDYEOF
# ^ Both roles share one domain/TLS cert, split by path — simpler than
# provisioning two certs. lib/ai-client.ts's PrivateEndpoint.baseUrl for this
# customer should be set to https://${domain} with the fast/premium model
# names distinguishing the calls (vLLM's --served-model-name makes this
# work: one Caddy instance, two backend containers, model name in the
# request body routes to the right one — see infra/README.md's routing note
# if you'd rather split by subdomain instead of path).
systemctl reload caddy

# ── 3. Per-role config for the updater + containers ──────────────────────────
mkdir -p /etc/quorum /opt/quorum
echo -n "$API_KEY"   > /etc/quorum/api-key
echo -n "$ADMIN_KEY" > /etc/quorum/admin-key
chmod 600 /etc/quorum/api-key /etc/quorum/admin-key

# Two env files — one per role — since check-and-update.sh runs once per
# role (two systemd timer instances, see below).
cat > /etc/quorum/updater-fast.env <<EOF
QUORUM_IMAGE=$QUORUM_IMAGE
QUORUM_CONTAINER_NAME=quorum-fast
QUORUM_LIVE_PORT=8001
QUORUM_STAGING_PORT=9001
QUORUM_MODEL_NAME=$FAST_MODEL
QUORUM_CUSTOMER_USER_ID=$CUSTOMER_USER_ID
EOF

cat > /etc/quorum/updater-premium.env <<EOF
QUORUM_IMAGE=$QUORUM_IMAGE
QUORUM_CONTAINER_NAME=quorum-premium
QUORUM_LIVE_PORT=8002
QUORUM_STAGING_PORT=9002
QUORUM_MODEL_NAME=$PREMIUM_MODEL
QUORUM_CUSTOMER_USER_ID=$CUSTOMER_USER_ID
EOF

# ── 4. Start both model containers for the first time ────────────────────────
docker run -d --restart unless-stopped --name quorum-fast --gpus all \
  -p 8001:8000 -e MODEL_NAME="$FAST_MODEL" -e API_KEY="$API_KEY" "$QUORUM_IMAGE"
docker run -d --restart unless-stopped --name quorum-premium --gpus all \
  -p 8002:8000 -e MODEL_NAME="$PREMIUM_MODEL" -e API_KEY="$API_KEY" "$QUORUM_IMAGE"

# ── 5. Auto-updater — one timer instance per role ─────────────────────────────
cp /opt/quorum-source/check-and-update.sh /opt/quorum/check-and-update.sh
chmod +x /opt/quorum/check-and-update.sh

for role in fast premium; do
  cp /opt/quorum-source/quorum-updater.service /etc/systemd/system/quorum-updater-$role.service
  sed -i "s#/etc/quorum/updater.env#/etc/quorum/updater-$role.env#" /etc/systemd/system/quorum-updater-$role.service
  cp /opt/quorum-source/quorum-updater.timer /etc/systemd/system/quorum-updater-$role.timer
  sed -i "s#quorum-updater.service#quorum-updater-$role.service#" /etc/systemd/system/quorum-updater-$role.timer
  systemctl enable quorum-updater-$role.timer
  systemctl start quorum-updater-$role.timer
done

# ── 6. First health-ping so private_deployments.last_healthy_at isn't null
#      from the moment of deploy ───────────────────────────────────────────────
sleep 60  # give the two containers a moment to finish loading before the first ping
curl -sf -X POST "https://app.quorum.example.com/api/admin/private-deployment-health" \
  -H "x-admin-key: $ADMIN_KEY" -H "Content-Type: application/json" \
  -d "{\"userId\":\"$CUSTOMER_USER_ID\",\"imageVersion\":\"initial-deploy\"}" \
  || echo "Initial health-ping failed (non-fatal) — the 15-minute timer will retry."

echo "Bootstrap complete."
