// app/api/nudge/unsubscribe/route.ts
// ── One-click unsubscribe for daily nudge emails ──────────────────────────────
//
// GET /api/nudge/unsubscribe?token=<signedToken>
//
// No auth required — the signed token is the credential.
// Token format: `{userId}.{hmac}` — generated by lib/nudge-token.ts
// Verified via HMAC-SHA256(userId, CRON_SECRET) — timing-safe compare.
//
// On valid token:
//   • Sets user_preferences.daily_nudge_opted_out = true for the user
//   • Returns a minimal HTML confirmation page (no redirect needed)
//
// On invalid/missing token:
//   • Returns 400 with a plain error page (no information leaked)
//
// Idempotent: calling twice is safe — upsert sets the column regardless.
//
// Note: if CRON_SECRET ever rotates, existing unsubscribe links in already-sent
// emails will return 400. Users can reply to email as fallback. Low risk at
// current scale.
// ─────────────────────────────────────────────────────────────────────────────

import { NextResponse }        from 'next/server'
import { createServiceClient } from '@/lib/supabase'
import { verifyUnsubToken }    from '@/lib/nudge-token'

// ── HTML responses ────────────────────────────────────────────────────────────

function confirmedHtml(appUrl: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Unsubscribed — Quorum</title>
</head>
<body style="background:#f5f4f0;margin:0;padding:80px 20px;font-family:'DM Sans',Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased">
  <div style="max-width:400px;margin:0 auto;text-align:center">

    <p style="color:#999;font-size:10px;letter-spacing:0.22em;text-transform:uppercase;margin:0 0 40px;font-family:monospace">
      Quorum &middot; Judgment Record
    </p>

    <p style="color:#1a1a1a;font-size:20px;font-weight:400;margin:0 0 16px;line-height:1.4">
      You&rsquo;re unsubscribed.
    </p>

    <p style="color:#888;font-size:14px;margin:0 0 40px;line-height:1.6">
      You won&rsquo;t receive daily nudges anymore.<br>
      Your record and all your decisions are still there.
    </p>

    <a href="${appUrl}"
       style="display:inline-block;background:#c9a84c;color:#0a0a12;text-decoration:none;
              padding:12px 24px;border-radius:8px;font-size:13px;font-weight:700;
              letter-spacing:0.04em">
      Back to Quorum &rarr;
    </a>

  </div>
</body>
</html>`
}

function errorHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Invalid link — Quorum</title>
</head>
<body style="background:#f5f4f0;margin:0;padding:80px 20px;font-family:'DM Sans',Helvetica,Arial,sans-serif">
  <div style="max-width:400px;margin:0 auto;text-align:center">
    <p style="color:#999;font-size:10px;letter-spacing:0.22em;text-transform:uppercase;margin:0 0 40px;font-family:monospace">
      Quorum &middot; Judgment Record
    </p>
    <p style="color:#1a1a1a;font-size:18px;font-weight:400;margin:0 0 16px">
      This link is no longer valid.
    </p>
    <p style="color:#888;font-size:14px;margin:0 0 40px;line-height:1.6">
      It may have expired or already been used.<br>
      Reply to any Quorum email to stop nudges manually.
    </p>
  </div>
</body>
</html>`
}

// ── Handler ───────────────────────────────────────────────────────────────────
export async function GET(req: Request) {
  const appUrl = (process.env.NEXT_PUBLIC_APP_URL ?? 'https://app.quorumvault.org').replace(/\/$/, '')

  // ── 1. Extract + verify token ─────────────────────────────────────────────
  const { searchParams } = new URL(req.url)
  const token  = searchParams.get('token') ?? ''
  const userId = verifyUnsubToken(token)

  if (!userId) {
    console.warn('[NudgeUnsub] Invalid or missing token')
    return new NextResponse(errorHtml(), {
      status: 400,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  // ── 2. Set opted-out flag ─────────────────────────────────────────────────
  // Upsert so the row is created even if link-sessions hasn't run for this user.
  const supabase = createServiceClient()

  const { error } = await supabase
    .from('user_preferences')
    .upsert(
      { user_id: userId, daily_nudge_opted_out: true },
      { onConflict: 'user_id' },
    )

  if (error) {
    console.error(`[NudgeUnsub] DB error for user ${userId.slice(0, 8)}:`, error.message)
    // Still return the confirmation page — worst case they get one more email
    // and click again. Don't expose DB errors to the browser.
  } else {
    console.log(`[NudgeUnsub] Opted out user ${userId.slice(0, 8)}`)
  }

  // ── 3. Confirm ────────────────────────────────────────────────────────────
  return new NextResponse(confirmedHtml(appUrl), {
    status: 200,
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  })
}
